// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Yessenchik/bydz-fitness-app/user-auth-service/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// DeleteEmailVerificationToken mocks base method.
func (m *MockUserRepository) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailVerificationToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailVerificationToken indicates an expected call of DeleteEmailVerificationToken.
func (mr *MockUserRepositoryMockRecorder) DeleteEmailVerificationToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).DeleteEmailVerificationToken), ctx, token)
}

// DeletePasswordResetToken mocks base method.
func (m *MockUserRepository) DeletePasswordResetToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePasswordResetToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePasswordResetToken indicates an expected call of DeletePasswordResetToken.
func (mr *MockUserRepositoryMockRecorder) DeletePasswordResetToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePasswordResetToken", reflect.TypeOf((*MockUserRepository)(nil).DeletePasswordResetToken), ctx, token)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetEmailVerificationToken mocks base method.
func (m *MockUserRepository) GetEmailVerificationToken(ctx context.Context, token string) (*domain.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationToken", ctx, token)
	ret0, _ := ret[0].(*domain.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationToken indicates an expected call of GetEmailVerificationToken.
func (mr *MockUserRepositoryMockRecorder) GetEmailVerificationToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).GetEmailVerificationToken), ctx, token)
}

// GetPasswordResetToken mocks base method.
func (m *MockUserRepository) GetPasswordResetToken(ctx context.Context, token string) (*domain.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordResetToken", ctx, token)
	ret0, _ := ret[0].(*domain.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordResetToken indicates an expected call of GetPasswordResetToken.
func (mr *MockUserRepositoryMockRecorder) GetPasswordResetToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordResetToken", reflect.TypeOf((*MockUserRepository)(nil).GetPasswordResetToken), ctx, token)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, filter domain.ListUsersFilter) ([]*domain.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, filter)
}

// SaveEmailVerificationToken mocks base method.
func (m *MockUserRepository) SaveEmailVerificationToken(ctx context.Context, t *domain.EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmailVerificationToken", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEmailVerificationToken indicates an expected call of SaveEmailVerificationToken.
func (mr *MockUserRepositoryMockRecorder) SaveEmailVerificationToken(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmailVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).SaveEmailVerificationToken), ctx, t)
}

// SavePasswordResetToken mocks base method.
func (m *MockUserRepository) SavePasswordResetToken(ctx context.Context, t *domain.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePasswordResetToken", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePasswordResetToken indicates an expected call of SavePasswordResetToken.
func (mr *MockUserRepositoryMockRecorder) SavePasswordResetToken(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePasswordResetToken", reflect.TypeOf((*MockUserRepository)(nil).SavePasswordResetToken), ctx, t)
}

// SoftDelete mocks base method.
func (m *MockUserRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserRepositoryMockRecorder) SoftDelete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// BlacklistToken mocks base method.
func (m *MockCacheRepository) BlacklistToken(ctx context.Context, tokenID string, ttlSeconds int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistToken", ctx, tokenID, ttlSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlacklistToken indicates an expected call of BlacklistToken.
func (mr *MockCacheRepositoryMockRecorder) BlacklistToken(ctx, tokenID, ttlSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistToken", reflect.TypeOf((*MockCacheRepository)(nil).BlacklistToken), ctx, tokenID, ttlSeconds)
}

// DeleteRefreshToken mocks base method.
func (m *MockCacheRepository) DeleteRefreshToken(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockCacheRepositoryMockRecorder) DeleteRefreshToken(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockCacheRepository)(nil).DeleteRefreshToken), ctx, userID)
}

// GetRefreshToken mocks base method.
func (m *MockCacheRepository) GetRefreshToken(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockCacheRepositoryMockRecorder) GetRefreshToken(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockCacheRepository)(nil).GetRefreshToken), ctx, userID)
}

// GetUserProfile mocks base method.
func (m *MockCacheRepository) GetUserProfile(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockCacheRepositoryMockRecorder) GetUserProfile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockCacheRepository)(nil).GetUserProfile), ctx, id)
}

// InvalidateUserProfile mocks base method.
func (m *MockCacheRepository) InvalidateUserProfile(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserProfile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserProfile indicates an expected call of InvalidateUserProfile.
func (mr *MockCacheRepositoryMockRecorder) InvalidateUserProfile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserProfile", reflect.TypeOf((*MockCacheRepository)(nil).InvalidateUserProfile), ctx, id)
}

// IsTokenBlacklisted mocks base method.
func (m *MockCacheRepository) IsTokenBlacklisted(ctx context.Context, tokenID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenBlacklisted", ctx, tokenID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenBlacklisted indicates an expected call of IsTokenBlacklisted.
func (mr *MockCacheRepositoryMockRecorder) IsTokenBlacklisted(ctx, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenBlacklisted", reflect.TypeOf((*MockCacheRepository)(nil).IsTokenBlacklisted), ctx, tokenID)
}

// SetRefreshToken mocks base method.
func (m *MockCacheRepository) SetRefreshToken(ctx context.Context, userID uuid.UUID, tokenID string, ttlSeconds int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefreshToken", ctx, userID, tokenID, ttlSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefreshToken indicates an expected call of SetRefreshToken.
func (mr *MockCacheRepositoryMockRecorder) SetRefreshToken(ctx, userID, tokenID, ttlSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefreshToken", reflect.TypeOf((*MockCacheRepository)(nil).SetRefreshToken), ctx, userID, tokenID, ttlSeconds)
}

// SetUserProfile mocks base method.
func (m *MockCacheRepository) SetUserProfile(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserProfile", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserProfile indicates an expected call of SetUserProfile.
func (mr *MockCacheRepositoryMockRecorder) SetUserProfile(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserProfile", reflect.TypeOf((*MockCacheRepository)(nil).SetUserProfile), ctx, user)
}

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockMessagePublisher) Publish(ctx context.Context, subject string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMessagePublisherMockRecorder) Publish(ctx, subject, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessagePublisher)(nil).Publish), ctx, subject, payload)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendPasswordResetEmail mocks base method.
func (m *MockEmailService) SendPasswordResetEmail(ctx context.Context, toEmail, firstName, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetEmail", ctx, toEmail, firstName, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetEmail indicates an expected call of SendPasswordResetEmail.
func (mr *MockEmailServiceMockRecorder) SendPasswordResetEmail(ctx, toEmail, firstName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetEmail", reflect.TypeOf((*MockEmailService)(nil).SendPasswordResetEmail), ctx, toEmail, firstName, token)
}

// SendVerificationEmail mocks base method.
func (m *MockEmailService) SendVerificationEmail(ctx context.Context, toEmail, firstName, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, toEmail, firstName, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockEmailServiceMockRecorder) SendVerificationEmail(ctx, toEmail, firstName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockEmailService)(nil).SendVerificationEmail), ctx, toEmail, firstName, token)
}

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// GenerateTokenPair mocks base method.
func (m *MockTokenManager) GenerateTokenPair(user *domain.User) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", user)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockTokenManagerMockRecorder) GenerateTokenPair(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockTokenManager)(nil).GenerateTokenPair), user)
}

// ParseAccessToken mocks base method.
func (m *MockTokenManager) ParseAccessToken(tokenString string) (*domain.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", tokenString)
	ret0, _ := ret[0].(*domain.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockTokenManagerMockRecorder) ParseAccessToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockTokenManager)(nil).ParseAccessToken), tokenString)
}

// ParseRefreshToken mocks base method.
func (m *MockTokenManager) ParseRefreshToken(tokenString string) (*domain.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", tokenString)
	ret0, _ := ret[0].(*domain.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockTokenManagerMockRecorder) ParseRefreshToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).ParseRefreshToken), tokenString)
}
