services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: membership-service
    ports:
      - "50051:50051"
    environment:
      APP_ENV: development

      GRPC_PORT: 50051

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym_password
      POSTGRES_DB: membership_db
      POSTGRES_SSL_MODE: disable

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

      NATS_URL: nats://nats:4222

      JWT_SECRET: super-secret-key

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: your_email@gmail.com
      SMTP_PASSWORD: your_app_password
      SMTP_FROM: your_email@gmail.com

      REQUEST_TIMEOUT_SECONDS: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      nats:
        condition: service_started
    networks:
      - membership-network

  postgres:
    image: postgres:16-alpine
    container_name: membership-postgres
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym_password
      POSTGRES_DB: membership_db
    ports:
      - "5433:5432"
    volumes:
      - membership_postgres_data:/var/lib/postgresql/data
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym -d membership_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - membership-network

  redis:
    image: redis:7-alpine
    container_name: membership-redis
    ports:
      - "6379:6379"
    networks:
      - membership-network

  nats:
    image: nats:2.10-alpine
    container_name: membership-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-m", "8222"]
    networks:
      - membership-network

  prometheus:
    image: prom/prometheus:latest
    container_name: membership-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - membership-network

  grafana:
    image: grafana/grafana:latest
    container_name: membership-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - membership_grafana_data:/var/lib/grafana
    networks:
      - membership-network

volumes:
  membership_postgres_data:
  membership_grafana_data:

networks:
  membership-network:
    driver: bridge