// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc1
// source: proto/membership.proto

package membershippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipAccessService_CreateMembershipPlan_FullMethodName      = "/membership.MembershipAccessService/CreateMembershipPlan"
	MembershipAccessService_GetMembershipPlan_FullMethodName         = "/membership.MembershipAccessService/GetMembershipPlan"
	MembershipAccessService_ListMembershipPlans_FullMethodName       = "/membership.MembershipAccessService/ListMembershipPlans"
	MembershipAccessService_UpdateMembershipPlan_FullMethodName      = "/membership.MembershipAccessService/UpdateMembershipPlan"
	MembershipAccessService_DeleteMembershipPlan_FullMethodName      = "/membership.MembershipAccessService/DeleteMembershipPlan"
	MembershipAccessService_CreateSubscription_FullMethodName        = "/membership.MembershipAccessService/CreateSubscription"
	MembershipAccessService_GetUserSubscription_FullMethodName       = "/membership.MembershipAccessService/GetUserSubscription"
	MembershipAccessService_ExtendSubscription_FullMethodName        = "/membership.MembershipAccessService/ExtendSubscription"
	MembershipAccessService_CancelSubscription_FullMethodName        = "/membership.MembershipAccessService/CancelSubscription"
	MembershipAccessService_CheckAccess_FullMethodName               = "/membership.MembershipAccessService/CheckAccess"
	MembershipAccessService_RegisterAttendance_FullMethodName        = "/membership.MembershipAccessService/RegisterAttendance"
	MembershipAccessService_GetUserAttendanceHistory_FullMethodName  = "/membership.MembershipAccessService/GetUserAttendanceHistory"
	MembershipAccessService_GetMonthlyAttendanceStats_FullMethodName = "/membership.MembershipAccessService/GetMonthlyAttendanceStats"
	MembershipAccessService_GetGlobalStats_FullMethodName            = "/membership.MembershipAccessService/GetGlobalStats"
)

// MembershipAccessServiceClient is the client API for MembershipAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MembershipAccessService is the main gRPC API for gym memberships,
// user subscriptions, attendance registration, access control and statistics.
type MembershipAccessServiceClient interface {
	// Membership plans
	CreateMembershipPlan(ctx context.Context, in *CreateMembershipPlanRequest, opts ...grpc.CallOption) (*MembershipPlanResponse, error)
	GetMembershipPlan(ctx context.Context, in *GetMembershipPlanRequest, opts ...grpc.CallOption) (*MembershipPlanResponse, error)
	ListMembershipPlans(ctx context.Context, in *ListMembershipPlansRequest, opts ...grpc.CallOption) (*ListMembershipPlansResponse, error)
	UpdateMembershipPlan(ctx context.Context, in *UpdateMembershipPlanRequest, opts ...grpc.CallOption) (*MembershipPlanResponse, error)
	DeleteMembershipPlan(ctx context.Context, in *DeleteMembershipPlanRequest, opts ...grpc.CallOption) (*DeleteMembershipPlanResponse, error)
	// Subscriptions
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	ExtendSubscription(ctx context.Context, in *ExtendSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error)
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
	// Attendance
	RegisterAttendance(ctx context.Context, in *RegisterAttendanceRequest, opts ...grpc.CallOption) (*AttendanceResponse, error)
	GetUserAttendanceHistory(ctx context.Context, in *GetUserAttendanceHistoryRequest, opts ...grpc.CallOption) (*GetUserAttendanceHistoryResponse, error)
	GetMonthlyAttendanceStats(ctx context.Context, in *GetMonthlyAttendanceStatsRequest, opts ...grpc.CallOption) (*MonthlyAttendanceStatsResponse, error)
	// Admin
	GetGlobalStats(ctx context.Context, in *GetGlobalStatsRequest, opts ...grpc.CallOption) (*GlobalStatsResponse, error)
}

type membershipAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipAccessServiceClient(cc grpc.ClientConnInterface) MembershipAccessServiceClient {
	return &membershipAccessServiceClient{cc}
}

func (c *membershipAccessServiceClient) CreateMembershipPlan(ctx context.Context, in *CreateMembershipPlanRequest, opts ...grpc.CallOption) (*MembershipPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipPlanResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_CreateMembershipPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) GetMembershipPlan(ctx context.Context, in *GetMembershipPlanRequest, opts ...grpc.CallOption) (*MembershipPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipPlanResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_GetMembershipPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) ListMembershipPlans(ctx context.Context, in *ListMembershipPlansRequest, opts ...grpc.CallOption) (*ListMembershipPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembershipPlansResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_ListMembershipPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) UpdateMembershipPlan(ctx context.Context, in *UpdateMembershipPlanRequest, opts ...grpc.CallOption) (*MembershipPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipPlanResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_UpdateMembershipPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) DeleteMembershipPlan(ctx context.Context, in *DeleteMembershipPlanRequest, opts ...grpc.CallOption) (*DeleteMembershipPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMembershipPlanResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_DeleteMembershipPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_GetUserSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) ExtendSubscription(ctx context.Context, in *ExtendSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_ExtendSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelSubscriptionResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_CancelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) RegisterAttendance(ctx context.Context, in *RegisterAttendanceRequest, opts ...grpc.CallOption) (*AttendanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttendanceResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_RegisterAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) GetUserAttendanceHistory(ctx context.Context, in *GetUserAttendanceHistoryRequest, opts ...grpc.CallOption) (*GetUserAttendanceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAttendanceHistoryResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_GetUserAttendanceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) GetMonthlyAttendanceStats(ctx context.Context, in *GetMonthlyAttendanceStatsRequest, opts ...grpc.CallOption) (*MonthlyAttendanceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyAttendanceStatsResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_GetMonthlyAttendanceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipAccessServiceClient) GetGlobalStats(ctx context.Context, in *GetGlobalStatsRequest, opts ...grpc.CallOption) (*GlobalStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalStatsResponse)
	err := c.cc.Invoke(ctx, MembershipAccessService_GetGlobalStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipAccessServiceServer is the server API for MembershipAccessService service.
// All implementations must embed UnimplementedMembershipAccessServiceServer
// for forward compatibility.
//
// MembershipAccessService is the main gRPC API for gym memberships,
// user subscriptions, attendance registration, access control and statistics.
type MembershipAccessServiceServer interface {
	// Membership plans
	CreateMembershipPlan(context.Context, *CreateMembershipPlanRequest) (*MembershipPlanResponse, error)
	GetMembershipPlan(context.Context, *GetMembershipPlanRequest) (*MembershipPlanResponse, error)
	ListMembershipPlans(context.Context, *ListMembershipPlansRequest) (*ListMembershipPlansResponse, error)
	UpdateMembershipPlan(context.Context, *UpdateMembershipPlanRequest) (*MembershipPlanResponse, error)
	DeleteMembershipPlan(context.Context, *DeleteMembershipPlanRequest) (*DeleteMembershipPlanResponse, error)
	// Subscriptions
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*SubscriptionResponse, error)
	GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*SubscriptionResponse, error)
	ExtendSubscription(context.Context, *ExtendSubscriptionRequest) (*SubscriptionResponse, error)
	CancelSubscription(context.Context, *CancelSubscriptionRequest) (*CancelSubscriptionResponse, error)
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	// Attendance
	RegisterAttendance(context.Context, *RegisterAttendanceRequest) (*AttendanceResponse, error)
	GetUserAttendanceHistory(context.Context, *GetUserAttendanceHistoryRequest) (*GetUserAttendanceHistoryResponse, error)
	GetMonthlyAttendanceStats(context.Context, *GetMonthlyAttendanceStatsRequest) (*MonthlyAttendanceStatsResponse, error)
	// Admin
	GetGlobalStats(context.Context, *GetGlobalStatsRequest) (*GlobalStatsResponse, error)
	mustEmbedUnimplementedMembershipAccessServiceServer()
}

// UnimplementedMembershipAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipAccessServiceServer struct{}

func (UnimplementedMembershipAccessServiceServer) CreateMembershipPlan(context.Context, *CreateMembershipPlanRequest) (*MembershipPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMembershipPlan not implemented")
}
func (UnimplementedMembershipAccessServiceServer) GetMembershipPlan(context.Context, *GetMembershipPlanRequest) (*MembershipPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembershipPlan not implemented")
}
func (UnimplementedMembershipAccessServiceServer) ListMembershipPlans(context.Context, *ListMembershipPlansRequest) (*ListMembershipPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembershipPlans not implemented")
}
func (UnimplementedMembershipAccessServiceServer) UpdateMembershipPlan(context.Context, *UpdateMembershipPlanRequest) (*MembershipPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMembershipPlan not implemented")
}
func (UnimplementedMembershipAccessServiceServer) DeleteMembershipPlan(context.Context, *DeleteMembershipPlanRequest) (*DeleteMembershipPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMembershipPlan not implemented")
}
func (UnimplementedMembershipAccessServiceServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedMembershipAccessServiceServer) GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSubscription not implemented")
}
func (UnimplementedMembershipAccessServiceServer) ExtendSubscription(context.Context, *ExtendSubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendSubscription not implemented")
}
func (UnimplementedMembershipAccessServiceServer) CancelSubscription(context.Context, *CancelSubscriptionRequest) (*CancelSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSubscription not implemented")
}
func (UnimplementedMembershipAccessServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedMembershipAccessServiceServer) RegisterAttendance(context.Context, *RegisterAttendanceRequest) (*AttendanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAttendance not implemented")
}
func (UnimplementedMembershipAccessServiceServer) GetUserAttendanceHistory(context.Context, *GetUserAttendanceHistoryRequest) (*GetUserAttendanceHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAttendanceHistory not implemented")
}
func (UnimplementedMembershipAccessServiceServer) GetMonthlyAttendanceStats(context.Context, *GetMonthlyAttendanceStatsRequest) (*MonthlyAttendanceStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyAttendanceStats not implemented")
}
func (UnimplementedMembershipAccessServiceServer) GetGlobalStats(context.Context, *GetGlobalStatsRequest) (*GlobalStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalStats not implemented")
}
func (UnimplementedMembershipAccessServiceServer) mustEmbedUnimplementedMembershipAccessServiceServer() {
}
func (UnimplementedMembershipAccessServiceServer) testEmbeddedByValue() {}

// UnsafeMembershipAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipAccessServiceServer will
// result in compilation errors.
type UnsafeMembershipAccessServiceServer interface {
	mustEmbedUnimplementedMembershipAccessServiceServer()
}

func RegisterMembershipAccessServiceServer(s grpc.ServiceRegistrar, srv MembershipAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipAccessService_ServiceDesc, srv)
}

func _MembershipAccessService_CreateMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).CreateMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_CreateMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).CreateMembershipPlan(ctx, req.(*CreateMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_GetMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).GetMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_GetMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).GetMembershipPlan(ctx, req.(*GetMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_ListMembershipPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).ListMembershipPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_ListMembershipPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).ListMembershipPlans(ctx, req.(*ListMembershipPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_UpdateMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).UpdateMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_UpdateMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).UpdateMembershipPlan(ctx, req.(*UpdateMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_DeleteMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).DeleteMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_DeleteMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).DeleteMembershipPlan(ctx, req.(*DeleteMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_GetUserSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).GetUserSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_GetUserSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).GetUserSubscription(ctx, req.(*GetUserSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_ExtendSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).ExtendSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_ExtendSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).ExtendSubscription(ctx, req.(*ExtendSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_CancelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).CancelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_CancelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).CancelSubscription(ctx, req.(*CancelSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_RegisterAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).RegisterAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_RegisterAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).RegisterAttendance(ctx, req.(*RegisterAttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_GetUserAttendanceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAttendanceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).GetUserAttendanceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_GetUserAttendanceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).GetUserAttendanceHistory(ctx, req.(*GetUserAttendanceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_GetMonthlyAttendanceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyAttendanceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).GetMonthlyAttendanceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_GetMonthlyAttendanceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).GetMonthlyAttendanceStats(ctx, req.(*GetMonthlyAttendanceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipAccessService_GetGlobalStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipAccessServiceServer).GetGlobalStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipAccessService_GetGlobalStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipAccessServiceServer).GetGlobalStats(ctx, req.(*GetGlobalStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipAccessService_ServiceDesc is the grpc.ServiceDesc for MembershipAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "membership.MembershipAccessService",
	HandlerType: (*MembershipAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMembershipPlan",
			Handler:    _MembershipAccessService_CreateMembershipPlan_Handler,
		},
		{
			MethodName: "GetMembershipPlan",
			Handler:    _MembershipAccessService_GetMembershipPlan_Handler,
		},
		{
			MethodName: "ListMembershipPlans",
			Handler:    _MembershipAccessService_ListMembershipPlans_Handler,
		},
		{
			MethodName: "UpdateMembershipPlan",
			Handler:    _MembershipAccessService_UpdateMembershipPlan_Handler,
		},
		{
			MethodName: "DeleteMembershipPlan",
			Handler:    _MembershipAccessService_DeleteMembershipPlan_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _MembershipAccessService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetUserSubscription",
			Handler:    _MembershipAccessService_GetUserSubscription_Handler,
		},
		{
			MethodName: "ExtendSubscription",
			Handler:    _MembershipAccessService_ExtendSubscription_Handler,
		},
		{
			MethodName: "CancelSubscription",
			Handler:    _MembershipAccessService_CancelSubscription_Handler,
		},
		{
			MethodName: "CheckAccess",
			Handler:    _MembershipAccessService_CheckAccess_Handler,
		},
		{
			MethodName: "RegisterAttendance",
			Handler:    _MembershipAccessService_RegisterAttendance_Handler,
		},
		{
			MethodName: "GetUserAttendanceHistory",
			Handler:    _MembershipAccessService_GetUserAttendanceHistory_Handler,
		},
		{
			MethodName: "GetMonthlyAttendanceStats",
			Handler:    _MembershipAccessService_GetMonthlyAttendanceStats_Handler,
		},
		{
			MethodName: "GetGlobalStats",
			Handler:    _MembershipAccessService_GetGlobalStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/membership.proto",
}
