root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/auth-service ./cmd/server"
bin = "./tmp/auth-service"
include_ext = ["go"]
exclude_dir = ["tmp", "gen"]
delay = 1000
stop_on_error = true

[log]
time = true