// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: proto/membership.proto

package membershippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED SubscriptionStatus = 0
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE      SubscriptionStatus = 1
	SubscriptionStatus_SUBSCRIPTION_STATUS_EXPIRED     SubscriptionStatus = 2
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELLED   SubscriptionStatus = 3
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_ACTIVE",
		2: "SUBSCRIPTION_STATUS_EXPIRED",
		3: "SUBSCRIPTION_STATUS_CANCELLED",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATUS_ACTIVE":      1,
		"SUBSCRIPTION_STATUS_EXPIRED":     2,
		"SUBSCRIPTION_STATUS_CANCELLED":   3,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_membership_proto_enumTypes[0].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_proto_membership_proto_enumTypes[0]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{0}
}

type MembershipPlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DurationMonths int32                  `protobuf:"varint,3,opt,name=duration_months,json=durationMonths,proto3" json:"duration_months,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IsDeleted      bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MembershipPlan) Reset() {
	*x = MembershipPlan{}
	mi := &file_proto_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipPlan) ProtoMessage() {}

func (x *MembershipPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipPlan.ProtoReflect.Descriptor instead.
func (*MembershipPlan) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MembershipPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MembershipPlan) GetDurationMonths() int32 {
	if x != nil {
		return x.DurationMonths
	}
	return 0
}

func (x *MembershipPlan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MembershipPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MembershipPlan) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *MembershipPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MembershipPlan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Subscription struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MembershipPlanId string                 `protobuf:"bytes,3,opt,name=membership_plan_id,json=membershipPlanId,proto3" json:"membership_plan_id,omitempty"`
	StartDate        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsActive         bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Status           SubscriptionStatus     `protobuf:"varint,7,opt,name=status,proto3,enum=membership.SubscriptionStatus" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetMembershipPlanId() string {
	if x != nil {
		return x.MembershipPlanId
	}
	return ""
}

func (x *Subscription) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Subscription) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Subscription) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Attendance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckInTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=check_in_time,json=checkInTime,proto3" json:"check_in_time,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendance) Reset() {
	*x = Attendance{}
	mi := &file_proto_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendance) ProtoMessage() {}

func (x *Attendance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendance.ProtoReflect.Descriptor instead.
func (*Attendance) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{2}
}

func (x *Attendance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attendance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Attendance) GetCheckInTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckInTime
	}
	return nil
}

func (x *Attendance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Attendance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateMembershipPlanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationMonths int32                  `protobuf:"varint,2,opt,name=duration_months,json=durationMonths,proto3" json:"duration_months,omitempty"`
	Price          float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMembershipPlanRequest) Reset() {
	*x = CreateMembershipPlanRequest{}
	mi := &file_proto_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipPlanRequest) ProtoMessage() {}

func (x *CreateMembershipPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipPlanRequest.ProtoReflect.Descriptor instead.
func (*CreateMembershipPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMembershipPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMembershipPlanRequest) GetDurationMonths() int32 {
	if x != nil {
		return x.DurationMonths
	}
	return 0
}

func (x *CreateMembershipPlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMembershipPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetMembershipPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipPlanRequest) Reset() {
	*x = GetMembershipPlanRequest{}
	mi := &file_proto_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipPlanRequest) ProtoMessage() {}

func (x *GetMembershipPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipPlanRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{4}
}

func (x *GetMembershipPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMembershipPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipPlansRequest) Reset() {
	*x = ListMembershipPlansRequest{}
	mi := &file_proto_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipPlansRequest) ProtoMessage() {}

func (x *ListMembershipPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipPlansRequest.ProtoReflect.Descriptor instead.
func (*ListMembershipPlansRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{5}
}

func (x *ListMembershipPlansRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMembershipPlansRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateMembershipPlanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DurationMonths int32                  `protobuf:"varint,3,opt,name=duration_months,json=durationMonths,proto3" json:"duration_months,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMembershipPlanRequest) Reset() {
	*x = UpdateMembershipPlanRequest{}
	mi := &file_proto_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipPlanRequest) ProtoMessage() {}

func (x *UpdateMembershipPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipPlanRequest.ProtoReflect.Descriptor instead.
func (*UpdateMembershipPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMembershipPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMembershipPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMembershipPlanRequest) GetDurationMonths() int32 {
	if x != nil {
		return x.DurationMonths
	}
	return 0
}

func (x *UpdateMembershipPlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMembershipPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteMembershipPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipPlanRequest) Reset() {
	*x = DeleteMembershipPlanRequest{}
	mi := &file_proto_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipPlanRequest) ProtoMessage() {}

func (x *DeleteMembershipPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipPlanRequest.ProtoReflect.Descriptor instead.
func (*DeleteMembershipPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMembershipPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMembershipPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipPlanResponse) Reset() {
	*x = DeleteMembershipPlanResponse{}
	mi := &file_proto_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipPlanResponse) ProtoMessage() {}

func (x *DeleteMembershipPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipPlanResponse.ProtoReflect.Descriptor instead.
func (*DeleteMembershipPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMembershipPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MembershipPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *MembershipPlan        `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipPlanResponse) Reset() {
	*x = MembershipPlanResponse{}
	mi := &file_proto_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipPlanResponse) ProtoMessage() {}

func (x *MembershipPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipPlanResponse.ProtoReflect.Descriptor instead.
func (*MembershipPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{9}
}

func (x *MembershipPlanResponse) GetPlan() *MembershipPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type ListMembershipPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*MembershipPlan      `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipPlansResponse) Reset() {
	*x = ListMembershipPlansResponse{}
	mi := &file_proto_membership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipPlansResponse) ProtoMessage() {}

func (x *ListMembershipPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipPlansResponse.ProtoReflect.Descriptor instead.
func (*ListMembershipPlansResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembershipPlansResponse) GetPlans() []*MembershipPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *ListMembershipPlansResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMembershipPlansResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MembershipPlanId string                 `protobuf:"bytes,2,opt,name=membership_plan_id,json=membershipPlanId,proto3" json:"membership_plan_id,omitempty"`
	UserEmail        string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_proto_membership_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetMembershipPlanId() string {
	if x != nil {
		return x.MembershipPlanId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_proto_membership_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExtendSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MembershipPlanId string                 `protobuf:"bytes,2,opt,name=membership_plan_id,json=membershipPlanId,proto3" json:"membership_plan_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtendSubscriptionRequest) Reset() {
	*x = ExtendSubscriptionRequest{}
	mi := &file_proto_membership_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSubscriptionRequest) ProtoMessage() {}

func (x *ExtendSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ExtendSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{13}
}

func (x *ExtendSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExtendSubscriptionRequest) GetMembershipPlanId() string {
	if x != nil {
		return x.MembershipPlanId
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_proto_membership_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{14}
}

func (x *CancelSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_proto_membership_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{15}
}

func (x *CancelSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_proto_membership_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{16}
}

func (x *SubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_proto_membership_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{17}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_proto_membership_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{18}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RegisterAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAttendanceRequest) Reset() {
	*x = RegisterAttendanceRequest{}
	mi := &file_proto_membership_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAttendanceRequest) ProtoMessage() {}

func (x *RegisterAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAttendanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterAttendanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    *Attendance            `protobuf:"bytes,1,opt,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceResponse) Reset() {
	*x = AttendanceResponse{}
	mi := &file_proto_membership_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceResponse) ProtoMessage() {}

func (x *AttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceResponse.ProtoReflect.Descriptor instead.
func (*AttendanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{20}
}

func (x *AttendanceResponse) GetAttendance() *Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

type GetUserAttendanceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAttendanceHistoryRequest) Reset() {
	*x = GetUserAttendanceHistoryRequest{}
	mi := &file_proto_membership_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAttendanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAttendanceHistoryRequest) ProtoMessage() {}

func (x *GetUserAttendanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAttendanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetUserAttendanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserAttendanceHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAttendanceHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserAttendanceHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserAttendanceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendances   []*Attendance          `protobuf:"bytes,1,rep,name=attendances,proto3" json:"attendances,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAttendanceHistoryResponse) Reset() {
	*x = GetUserAttendanceHistoryResponse{}
	mi := &file_proto_membership_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAttendanceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAttendanceHistoryResponse) ProtoMessage() {}

func (x *GetUserAttendanceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAttendanceHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserAttendanceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserAttendanceHistoryResponse) GetAttendances() []*Attendance {
	if x != nil {
		return x.Attendances
	}
	return nil
}

func (x *GetUserAttendanceHistoryResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserAttendanceHistoryResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMonthlyAttendanceStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyAttendanceStatsRequest) Reset() {
	*x = GetMonthlyAttendanceStatsRequest{}
	mi := &file_proto_membership_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyAttendanceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyAttendanceStatsRequest) ProtoMessage() {}

func (x *GetMonthlyAttendanceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyAttendanceStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyAttendanceStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{23}
}

func (x *GetMonthlyAttendanceStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MonthlyAttendanceStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VisitsThisMonth int64                  `protobuf:"varint,2,opt,name=visits_this_month,json=visitsThisMonth,proto3" json:"visits_this_month,omitempty"`
	VisitsLastMonth int64                  `protobuf:"varint,3,opt,name=visits_last_month,json=visitsLastMonth,proto3" json:"visits_last_month,omitempty"`
	TotalVisits     int64                  `protobuf:"varint,4,opt,name=total_visits,json=totalVisits,proto3" json:"total_visits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MonthlyAttendanceStatsResponse) Reset() {
	*x = MonthlyAttendanceStatsResponse{}
	mi := &file_proto_membership_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyAttendanceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyAttendanceStatsResponse) ProtoMessage() {}

func (x *MonthlyAttendanceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyAttendanceStatsResponse.ProtoReflect.Descriptor instead.
func (*MonthlyAttendanceStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{24}
}

func (x *MonthlyAttendanceStatsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MonthlyAttendanceStatsResponse) GetVisitsThisMonth() int64 {
	if x != nil {
		return x.VisitsThisMonth
	}
	return 0
}

func (x *MonthlyAttendanceStatsResponse) GetVisitsLastMonth() int64 {
	if x != nil {
		return x.VisitsLastMonth
	}
	return 0
}

func (x *MonthlyAttendanceStatsResponse) GetTotalVisits() int64 {
	if x != nil {
		return x.TotalVisits
	}
	return 0
}

type GetGlobalStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalStatsRequest) Reset() {
	*x = GetGlobalStatsRequest{}
	mi := &file_proto_membership_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalStatsRequest) ProtoMessage() {}

func (x *GetGlobalStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{25}
}

type GlobalStatsResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ActiveSubscriptionsCount int64                  `protobuf:"varint,1,opt,name=active_subscriptions_count,json=activeSubscriptionsCount,proto3" json:"active_subscriptions_count,omitempty"`
	VisitsThisMonth          int64                  `protobuf:"varint,2,opt,name=visits_this_month,json=visitsThisMonth,proto3" json:"visits_this_month,omitempty"`
	TotalVisits              int64                  `protobuf:"varint,3,opt,name=total_visits,json=totalVisits,proto3" json:"total_visits,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GlobalStatsResponse) Reset() {
	*x = GlobalStatsResponse{}
	mi := &file_proto_membership_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStatsResponse) ProtoMessage() {}

func (x *GlobalStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStatsResponse.ProtoReflect.Descriptor instead.
func (*GlobalStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_proto_rawDescGZIP(), []int{26}
}

func (x *GlobalStatsResponse) GetActiveSubscriptionsCount() int64 {
	if x != nil {
		return x.ActiveSubscriptionsCount
	}
	return 0
}

func (x *GlobalStatsResponse) GetVisitsThisMonth() int64 {
	if x != nil {
		return x.VisitsThisMonth
	}
	return 0
}

func (x *GlobalStatsResponse) GetTotalVisits() int64 {
	if x != nil {
		return x.TotalVisits
	}
	return 0
}

var File_proto_membership_proto protoreflect.FileDescriptor

const file_proto_membership_proto_rawDesc = "" +
	"\n" +
	"\x16proto/membership.proto\x12\n" +
	"membership\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x02\n" +
	"\x0eMembershipPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fduration_months\x18\x03 \x01(\x05R\x0edurationMonths\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa2\x03\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x12membership_plan_id\x18\x03 \x01(\tR\x10membershipPlanId\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x126\n" +
	"\x06status\x18\a \x01(\x0e2\x1e.membership.SubscriptionStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc4\x01\n" +
	"\n" +
	"Attendance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12>\n" +
	"\rcheck_in_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcheckInTime\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x92\x01\n" +
	"\x1bCreateMembershipPlanRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fduration_months\x18\x02 \x01(\x05R\x0edurationMonths\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"*\n" +
	"\x18GetMembershipPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x1aListMembershipPlansRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xa2\x01\n" +
	"\x1bUpdateMembershipPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fduration_months\x18\x03 \x01(\x05R\x0edurationMonths\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"-\n" +
	"\x1bDeleteMembershipPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x1cDeleteMembershipPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x16MembershipPlanResponse\x12.\n" +
	"\x04plan\x18\x01 \x01(\v2\x1a.membership.MembershipPlanR\x04plan\"}\n" +
	"\x1bListMembershipPlansResponse\x120\n" +
	"\x05plans\x18\x01 \x03(\v2\x1a.membership.MembershipPlanR\x05plans\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x81\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12membership_plan_id\x18\x02 \x01(\tR\x10membershipPlanId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\"5\n" +
	"\x1aGetUserSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"b\n" +
	"\x19ExtendSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12membership_plan_id\x18\x02 \x01(\tR\x10membershipPlanId\"4\n" +
	"\x19CancelSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\x1aCancelSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x14SubscriptionResponse\x12<\n" +
	"\fsubscription\x18\x01 \x01(\v2\x18.membership.SubscriptionR\fsubscription\"-\n" +
	"\x12CheckAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"4\n" +
	"\x19RegisterAttendanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x12AttendanceResponse\x126\n" +
	"\n" +
	"attendance\x18\x01 \x01(\v2\x16.membership.AttendanceR\n" +
	"attendance\"h\n" +
	"\x1fGetUserAttendanceHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8a\x01\n" +
	" GetUserAttendanceHistoryResponse\x128\n" +
	"\vattendances\x18\x01 \x03(\v2\x16.membership.AttendanceR\vattendances\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\";\n" +
	" GetMonthlyAttendanceStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb4\x01\n" +
	"\x1eMonthlyAttendanceStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x11visits_this_month\x18\x02 \x01(\x03R\x0fvisitsThisMonth\x12*\n" +
	"\x11visits_last_month\x18\x03 \x01(\x03R\x0fvisitsLastMonth\x12!\n" +
	"\ftotal_visits\x18\x04 \x01(\x03R\vtotalVisits\"\x17\n" +
	"\x15GetGlobalStatsRequest\"\xa2\x01\n" +
	"\x13GlobalStatsResponse\x12<\n" +
	"\x1aactive_subscriptions_count\x18\x01 \x01(\x03R\x18activeSubscriptionsCount\x12*\n" +
	"\x11visits_this_month\x18\x02 \x01(\x03R\x0fvisitsThisMonth\x12!\n" +
	"\ftotal_visits\x18\x03 \x01(\x03R\vtotalVisits*\x9d\x01\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATUS_EXPIRED\x10\x02\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_CANCELLED\x10\x032\x8a\v\n" +
	"\x17MembershipAccessService\x12c\n" +
	"\x14CreateMembershipPlan\x12'.membership.CreateMembershipPlanRequest\x1a\".membership.MembershipPlanResponse\x12]\n" +
	"\x11GetMembershipPlan\x12$.membership.GetMembershipPlanRequest\x1a\".membership.MembershipPlanResponse\x12f\n" +
	"\x13ListMembershipPlans\x12&.membership.ListMembershipPlansRequest\x1a'.membership.ListMembershipPlansResponse\x12c\n" +
	"\x14UpdateMembershipPlan\x12'.membership.UpdateMembershipPlanRequest\x1a\".membership.MembershipPlanResponse\x12i\n" +
	"\x14DeleteMembershipPlan\x12'.membership.DeleteMembershipPlanRequest\x1a(.membership.DeleteMembershipPlanResponse\x12]\n" +
	"\x12CreateSubscription\x12%.membership.CreateSubscriptionRequest\x1a .membership.SubscriptionResponse\x12_\n" +
	"\x13GetUserSubscription\x12&.membership.GetUserSubscriptionRequest\x1a .membership.SubscriptionResponse\x12]\n" +
	"\x12ExtendSubscription\x12%.membership.ExtendSubscriptionRequest\x1a .membership.SubscriptionResponse\x12c\n" +
	"\x12CancelSubscription\x12%.membership.CancelSubscriptionRequest\x1a&.membership.CancelSubscriptionResponse\x12N\n" +
	"\vCheckAccess\x12\x1e.membership.CheckAccessRequest\x1a\x1f.membership.CheckAccessResponse\x12[\n" +
	"\x12RegisterAttendance\x12%.membership.RegisterAttendanceRequest\x1a\x1e.membership.AttendanceResponse\x12u\n" +
	"\x18GetUserAttendanceHistory\x12+.membership.GetUserAttendanceHistoryRequest\x1a,.membership.GetUserAttendanceHistoryResponse\x12u\n" +
	"\x19GetMonthlyAttendanceStats\x12,.membership.GetMonthlyAttendanceStatsRequest\x1a*.membership.MonthlyAttendanceStatsResponse\x12T\n" +
	"\x0eGetGlobalStats\x12!.membership.GetGlobalStatsRequest\x1a\x1f.membership.GlobalStatsResponseB'Z%membership-service/proto/membershippbb\x06proto3"

var (
	file_proto_membership_proto_rawDescOnce sync.Once
	file_proto_membership_proto_rawDescData []byte
)

func file_proto_membership_proto_rawDescGZIP() []byte {
	file_proto_membership_proto_rawDescOnce.Do(func() {
		file_proto_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_membership_proto_rawDesc), len(file_proto_membership_proto_rawDesc)))
	})
	return file_proto_membership_proto_rawDescData
}

var file_proto_membership_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_membership_proto_goTypes = []any{
	(SubscriptionStatus)(0),                  // 0: membership.SubscriptionStatus
	(*MembershipPlan)(nil),                   // 1: membership.MembershipPlan
	(*Subscription)(nil),                     // 2: membership.Subscription
	(*Attendance)(nil),                       // 3: membership.Attendance
	(*CreateMembershipPlanRequest)(nil),      // 4: membership.CreateMembershipPlanRequest
	(*GetMembershipPlanRequest)(nil),         // 5: membership.GetMembershipPlanRequest
	(*ListMembershipPlansRequest)(nil),       // 6: membership.ListMembershipPlansRequest
	(*UpdateMembershipPlanRequest)(nil),      // 7: membership.UpdateMembershipPlanRequest
	(*DeleteMembershipPlanRequest)(nil),      // 8: membership.DeleteMembershipPlanRequest
	(*DeleteMembershipPlanResponse)(nil),     // 9: membership.DeleteMembershipPlanResponse
	(*MembershipPlanResponse)(nil),           // 10: membership.MembershipPlanResponse
	(*ListMembershipPlansResponse)(nil),      // 11: membership.ListMembershipPlansResponse
	(*CreateSubscriptionRequest)(nil),        // 12: membership.CreateSubscriptionRequest
	(*GetUserSubscriptionRequest)(nil),       // 13: membership.GetUserSubscriptionRequest
	(*ExtendSubscriptionRequest)(nil),        // 14: membership.ExtendSubscriptionRequest
	(*CancelSubscriptionRequest)(nil),        // 15: membership.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil),       // 16: membership.CancelSubscriptionResponse
	(*SubscriptionResponse)(nil),             // 17: membership.SubscriptionResponse
	(*CheckAccessRequest)(nil),               // 18: membership.CheckAccessRequest
	(*CheckAccessResponse)(nil),              // 19: membership.CheckAccessResponse
	(*RegisterAttendanceRequest)(nil),        // 20: membership.RegisterAttendanceRequest
	(*AttendanceResponse)(nil),               // 21: membership.AttendanceResponse
	(*GetUserAttendanceHistoryRequest)(nil),  // 22: membership.GetUserAttendanceHistoryRequest
	(*GetUserAttendanceHistoryResponse)(nil), // 23: membership.GetUserAttendanceHistoryResponse
	(*GetMonthlyAttendanceStatsRequest)(nil), // 24: membership.GetMonthlyAttendanceStatsRequest
	(*MonthlyAttendanceStatsResponse)(nil),   // 25: membership.MonthlyAttendanceStatsResponse
	(*GetGlobalStatsRequest)(nil),            // 26: membership.GetGlobalStatsRequest
	(*GlobalStatsResponse)(nil),              // 27: membership.GlobalStatsResponse
	(*timestamppb.Timestamp)(nil),            // 28: google.protobuf.Timestamp
}
var file_proto_membership_proto_depIdxs = []int32{
	28, // 0: membership.MembershipPlan.created_at:type_name -> google.protobuf.Timestamp
	28, // 1: membership.MembershipPlan.updated_at:type_name -> google.protobuf.Timestamp
	28, // 2: membership.Subscription.start_date:type_name -> google.protobuf.Timestamp
	28, // 3: membership.Subscription.end_date:type_name -> google.protobuf.Timestamp
	0,  // 4: membership.Subscription.status:type_name -> membership.SubscriptionStatus
	28, // 5: membership.Subscription.created_at:type_name -> google.protobuf.Timestamp
	28, // 6: membership.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	28, // 7: membership.Attendance.check_in_time:type_name -> google.protobuf.Timestamp
	28, // 8: membership.Attendance.created_at:type_name -> google.protobuf.Timestamp
	1,  // 9: membership.MembershipPlanResponse.plan:type_name -> membership.MembershipPlan
	1,  // 10: membership.ListMembershipPlansResponse.plans:type_name -> membership.MembershipPlan
	2,  // 11: membership.SubscriptionResponse.subscription:type_name -> membership.Subscription
	3,  // 12: membership.AttendanceResponse.attendance:type_name -> membership.Attendance
	3,  // 13: membership.GetUserAttendanceHistoryResponse.attendances:type_name -> membership.Attendance
	4,  // 14: membership.MembershipAccessService.CreateMembershipPlan:input_type -> membership.CreateMembershipPlanRequest
	5,  // 15: membership.MembershipAccessService.GetMembershipPlan:input_type -> membership.GetMembershipPlanRequest
	6,  // 16: membership.MembershipAccessService.ListMembershipPlans:input_type -> membership.ListMembershipPlansRequest
	7,  // 17: membership.MembershipAccessService.UpdateMembershipPlan:input_type -> membership.UpdateMembershipPlanRequest
	8,  // 18: membership.MembershipAccessService.DeleteMembershipPlan:input_type -> membership.DeleteMembershipPlanRequest
	12, // 19: membership.MembershipAccessService.CreateSubscription:input_type -> membership.CreateSubscriptionRequest
	13, // 20: membership.MembershipAccessService.GetUserSubscription:input_type -> membership.GetUserSubscriptionRequest
	14, // 21: membership.MembershipAccessService.ExtendSubscription:input_type -> membership.ExtendSubscriptionRequest
	15, // 22: membership.MembershipAccessService.CancelSubscription:input_type -> membership.CancelSubscriptionRequest
	18, // 23: membership.MembershipAccessService.CheckAccess:input_type -> membership.CheckAccessRequest
	20, // 24: membership.MembershipAccessService.RegisterAttendance:input_type -> membership.RegisterAttendanceRequest
	22, // 25: membership.MembershipAccessService.GetUserAttendanceHistory:input_type -> membership.GetUserAttendanceHistoryRequest
	24, // 26: membership.MembershipAccessService.GetMonthlyAttendanceStats:input_type -> membership.GetMonthlyAttendanceStatsRequest
	26, // 27: membership.MembershipAccessService.GetGlobalStats:input_type -> membership.GetGlobalStatsRequest
	10, // 28: membership.MembershipAccessService.CreateMembershipPlan:output_type -> membership.MembershipPlanResponse
	10, // 29: membership.MembershipAccessService.GetMembershipPlan:output_type -> membership.MembershipPlanResponse
	11, // 30: membership.MembershipAccessService.ListMembershipPlans:output_type -> membership.ListMembershipPlansResponse
	10, // 31: membership.MembershipAccessService.UpdateMembershipPlan:output_type -> membership.MembershipPlanResponse
	9,  // 32: membership.MembershipAccessService.DeleteMembershipPlan:output_type -> membership.DeleteMembershipPlanResponse
	17, // 33: membership.MembershipAccessService.CreateSubscription:output_type -> membership.SubscriptionResponse
	17, // 34: membership.MembershipAccessService.GetUserSubscription:output_type -> membership.SubscriptionResponse
	17, // 35: membership.MembershipAccessService.ExtendSubscription:output_type -> membership.SubscriptionResponse
	16, // 36: membership.MembershipAccessService.CancelSubscription:output_type -> membership.CancelSubscriptionResponse
	19, // 37: membership.MembershipAccessService.CheckAccess:output_type -> membership.CheckAccessResponse
	21, // 38: membership.MembershipAccessService.RegisterAttendance:output_type -> membership.AttendanceResponse
	23, // 39: membership.MembershipAccessService.GetUserAttendanceHistory:output_type -> membership.GetUserAttendanceHistoryResponse
	25, // 40: membership.MembershipAccessService.GetMonthlyAttendanceStats:output_type -> membership.MonthlyAttendanceStatsResponse
	27, // 41: membership.MembershipAccessService.GetGlobalStats:output_type -> membership.GlobalStatsResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_membership_proto_init() }
func file_proto_membership_proto_init() {
	if File_proto_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_membership_proto_rawDesc), len(file_proto_membership_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_membership_proto_goTypes,
		DependencyIndexes: file_proto_membership_proto_depIdxs,
		EnumInfos:         file_proto_membership_proto_enumTypes,
		MessageInfos:      file_proto_membership_proto_msgTypes,
	}.Build()
	File_proto_membership_proto = out.File
	file_proto_membership_proto_goTypes = nil
	file_proto_membership_proto_depIdxs = nil
}
